openapi: 3.0.1
info:
  title: Nashville Parcel API
  description: API for looking up Metro Nashville parcel information by APN.
  version: "1.0.0"
servers:
  - url: https://chatgpt-gis-vercel1.vercel.app
paths:
  /api/parcel:
    get:
      operationId: getParcel
      summary: Look up a parcel by APN
      parameters:
        - in: query
          name: apn
          schema:
            type: string
          required: true
          description: Assessor’s Parcel Number (APN)
      responses:
        "200":
          description: Successful parcel lookup
          content:
            application/json:
              schema:
                type: object
                properties:
                  apn:
                    type: string
                  owner:
                    type: string
                  address:
                    type: string
                  acreage:
                    type: number
                  land_use:
                    type: string
                  zoning:
                    type: string
                  mailing_address:
                    type: string
                  city:
                    type: string
                  zip:
                    type: string
  /api/hello:
    get:
      operationId: hello
      summary: Health check endpoint
      responses:
        "200":
          description: Returns hello message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
