openapi: 3.0.1
info:
  title: Nashville GIS Parcels API
  description: API for retrieving parcel data in Nashville and Tennessee.
  version: "1.0.0"

servers:
  - url: https://chatgpt-gis-vercel1.vercel.app

paths:
  /api/hello:
    get:
      summary: Hello endpoint test
      operationId: getHello
      responses:
        '200':
          description: Returns a simple hello message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /api/parcel:
    get:
      summary: Get parcel details by APN
      operationId: getParcel
      parameters:
        - in: query
          name: apn
          schema:
            type: string
          required: true
          description: Assessor's Parcel Number
      responses:
        '200':
          description: Parcel details response
          content:
            application/json:
              schema:
                type: object
                properties:
                  apn:
                    type: string
                  owner:
                    type: string
                  address:
                    type: string
                  acreage:
                    type: number
